[mdzk]
backlinks-header = "Backlinks"
authors = ["kmaasrud"]
language = "en"
multilingual = false
src = "notes"
title = "Zettelkasten"
ignore = [
    "templates/",
]

[output.html]
copy-fonts = false
no-section-label = true

[output.html.fold]
enable = true
