[mdzk]
backlinks-header = "Backlinks"
authors = ["kmaasrud"]
language = "en"
multilingual = false
src = "notes"
title = "Zettelkasten"
ignore = [
    "templates/",
    ".obsidian/",
]

[output.html]
site-url = "/brain"
no-section-label = true

[output.html.fold]
enable = true
