[book]
authors = ["kmaasrud"]
language = "en"
multilingual = false
src = "zettels"
title = "Zettelkasten"

[build]
build-dir = "out"
create-missing = true
use-default-preprocessors = true

[output.html]
no-section-label = true
