[book]
authors = ["kmaasrud"]
language = "en"
multilingual = false
src = "zettels"
title = "Zettelkasten"

[build]
build-dir = "out"
create-missing = true
use-default-preprocessors = true

[output.html]
copy-fonts = false
no-section-label = true
site-url = "/brain/"

[output.html.print]
enable = false

[preprocessor.backlinks]
header = "Backlinks"
